name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:${{ github.sha }}

    - name: Run tests
      run: |
        docker-compose up -d
        docker-compose exec db mysqladmin ping -h localhost -u myuser -pmypassword --wait --silent
        docker-compose exec app npm test

    - name: Deploy to Digital Ocean
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key root@${{ secrets.DROPLET_IP }} << 'EOF'
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:${{ github.sha }}
        docker-compose down
        sleep 10  # Adiciona um delay para garantir que o banco de dados esteja pronto
        docker-compose up -d
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
